relocalization_bin_file: /home/firefly/ros2_ws/src/odin_ros_driver/map/B5/map_20260424_110803.bin
relocalization_pcd_file: /home/firefly/ros2_ws/src/odin_ros_driver/map/B5/Relocation_Map.pcd
map_package_dir: /home/firefly/maps/B5
show_rviz: false
show_map_gui: false
publish_d1_odom: false
use_static_odom_to_base: true
