global_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 0.0 
  publish_frequency: 0.0 
  static_map: false
  cost_scaling_factor: 10.0

  # 清空所有 2D/3D 膨胀与障碍物图层，零 CPU 占用，零传感器订阅
  plugins: []
