local_costmap:
  global_frame: odom
  robot_base_frame: base_link
  update_frequency: 0.0 
  publish_frequency: 0.0 

  static_map: false
  rolling_window: true
  width: 2.5
  height: 2.5
  cost_scaling_factor: 5

  # 清空所有 2D/3D 膨胀与障碍物图层，零 CPU 占用，零传感器订阅
  plugins: []
